# settings.yaml

default:
  DEBUG: true
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: mysecretpassword
  DB_NAME: blog

docker:
  DEBUG: true
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASS: password
  DB_NAME: blog